jobs:
- job: Linux_AppImage
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    submodules: true
  - script: sudo apt install -y protobuf-compiler libprotobuf-dev
    displayName: Install protobuf
  - bash: ci/build_onnx2bnn.sh
    displayName: Build
  - bash: ci/build_appimage.sh
    displayName: Build AppImage
  - task: CopyFiles@2
    inputs:
        contents: 'onnx2bnn.AppImage'
        targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: onnx2bnn AppImage
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'dabnn release'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      assets: '$(Build.ArtifactStagingDirectory)/onnx2bnn.AppImage'
- job: Windows_Python_Package
  pool:
      vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - powershell: |
      Write-Host "This works: $env:TWINE_USERNAME"    # Recommended
      Write-Host "This works: $env:TWINE_PASSWORD"    # Recommended
    workingDirectory: tools/onnx2bnn/python/
    env:
      TWINE_USERNAME: $(twineUsername)
      TWINE_PASSWORD: $(twinePassword)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5' 
      addToPath: true
      architecture: 'x64'
  - script: python -m pip install --user --upgrade setuptools wheel twine
    displayName: Install setuptools, wheel and twine
  - script: python setup.py sdist bdist_wheel
    workingDirectory: tools/onnx2bnn/python/
    displayName: Build onnx2bnn python package
  - script: python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
    workingDirectory: tools/onnx2bnn/python/
    env:
      TWINE_USERNAME: $(twineUsername)
      TWINE_PASSWORD: $(twinePassword)
