jobs:
- job: Linux_AppImage
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    submodules: true
  - script: sudo apt install -y cmake protobuf-compiler libprotobuf-dev
    displayName: Install cmake 3.5.1 and protobuf
  - bash: ci/build_onnx2bnn.sh
    displayName: Build
  - bash: ci/build_appimage.sh
    displayName: Build AppImage
  - task: CopyFiles@2
    inputs:
        contents: 'onnx2bnn.AppImage'
        targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: onnx2bnn AppImage
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'dabnn release'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      assets: '$(Build.ArtifactStagingDirectory)/onnx2bnn.AppImage'
- job: Windows_Python_Package
  pool:
      vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - script: python3 tools/onnx2bnn/python/setup.py
    workingDirectory: tools/onnx2bnn/python/
    displayName: Build onnx2bnn python package
